export { default as avatarlogo } from "./avtarlogo.png";
export { default as poster } from "./poster.jpg";
export { default as poster02 } from "./poster02.png";
export { default as cast01 } from "./cast01.jpg";
export { default as cast02 } from "./cast02.jpg";
export { default as cast03 } from "./cast03.jpg";
export { default as cast04 } from "./cast04.jpg";
export { default as cast05 } from "./cast05.jpg";
export { default as cast06 } from "./cast06.jpg";
